[package]
name = "atlasfetch"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.38.0"
sys-info = "0.9.1"
chrono = "0.4.43"
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
